package entity;
// Generated Dec 12, 2014 9:07:56 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Anpham generated by hbm2java
 */
@Entity
@Table(name="ANPHAM"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Anpham  implements java.io.Serializable {


     private int idAnpham;
     private Bmsophanloai bmsophanloai;
     private Bmtacgia bmtacgia;
     private Bmnxb bmnxb;
     private String tenAnpham;
     private String cqChuquan;
     private String dcToasoan;
     private Integer dkxb;
     private Set<BmChuongtapchi> bmChuongtapchis = new HashSet<BmChuongtapchi>(0);
     private Set<BmKytapchi> bmKytapchis = new HashSet<BmKytapchi>(0);

    public Anpham() {
    }

	
    public Anpham(int idAnpham) {
        this.idAnpham = idAnpham;
    }
    public Anpham(int idAnpham, Bmsophanloai bmsophanloai, Bmtacgia bmtacgia, Bmnxb bmnxb, String tenAnpham, String cqChuquan, String dcToasoan, Integer dkxb, Set<BmChuongtapchi> bmChuongtapchis, Set<BmKytapchi> bmKytapchis) {
       this.idAnpham = idAnpham;
       this.bmsophanloai = bmsophanloai;
       this.bmtacgia = bmtacgia;
       this.bmnxb = bmnxb;
       this.tenAnpham = tenAnpham;
       this.cqChuquan = cqChuquan;
       this.dcToasoan = dcToasoan;
       this.dkxb = dkxb;
       this.bmChuongtapchis = bmChuongtapchis;
       this.bmKytapchis = bmKytapchis;
    }
   
     @Id 

    
    @Column(name="ID_ANPHAM", unique=true, nullable=false)
    public int getIdAnpham() {
        return this.idAnpham;
    }
    
    public void setIdAnpham(int idAnpham) {
        this.idAnpham = idAnpham;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SOPHANLOAI")
    public Bmsophanloai getBmsophanloai() {
        return this.bmsophanloai;
    }
    
    public void setBmsophanloai(Bmsophanloai bmsophanloai) {
        this.bmsophanloai = bmsophanloai;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TONGBT")
    public Bmtacgia getBmtacgia() {
        return this.bmtacgia;
    }
    
    public void setBmtacgia(Bmtacgia bmtacgia) {
        this.bmtacgia = bmtacgia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NXB")
    public Bmnxb getBmnxb() {
        return this.bmnxb;
    }
    
    public void setBmnxb(Bmnxb bmnxb) {
        this.bmnxb = bmnxb;
    }

    
    @Column(name="TEN_ANPHAM")
    public String getTenAnpham() {
        return this.tenAnpham;
    }
    
    public void setTenAnpham(String tenAnpham) {
        this.tenAnpham = tenAnpham;
    }

    
    @Column(name="CQ_CHUQUAN")
    public String getCqChuquan() {
        return this.cqChuquan;
    }
    
    public void setCqChuquan(String cqChuquan) {
        this.cqChuquan = cqChuquan;
    }

    
    @Column(name="DC_TOASOAN")
    public String getDcToasoan() {
        return this.dcToasoan;
    }
    
    public void setDcToasoan(String dcToasoan) {
        this.dcToasoan = dcToasoan;
    }

    
    @Column(name="DKXB")
    public Integer getDkxb() {
        return this.dkxb;
    }
    
    public void setDkxb(Integer dkxb) {
        this.dkxb = dkxb;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="anpham")
    public Set<BmChuongtapchi> getBmChuongtapchis() {
        return this.bmChuongtapchis;
    }
    
    public void setBmChuongtapchis(Set<BmChuongtapchi> bmChuongtapchis) {
        this.bmChuongtapchis = bmChuongtapchis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="anpham")
    public Set<BmKytapchi> getBmKytapchis() {
        return this.bmKytapchis;
    }
    
    public void setBmKytapchis(Set<BmKytapchi> bmKytapchis) {
        this.bmKytapchis = bmKytapchis;
    }




}


