package entity;
// Generated Dec 12, 2014 5:30:45 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BmChuongtapchi generated by hbm2java
 */
@Entity
@Table(name="BM_CHUONGTAPCHI"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class BmChuongtapchi  implements java.io.Serializable {


     private int idChuong;
     private Anpham anpham;
     private Serializable tenChuong;
     private String noiDung;

    public BmChuongtapchi() {
    }

	
    public BmChuongtapchi(int idChuong) {
        this.idChuong = idChuong;
    }
    public BmChuongtapchi(int idChuong, Anpham anpham, Serializable tenChuong, String noiDung) {
       this.idChuong = idChuong;
       this.anpham = anpham;
       this.tenChuong = tenChuong;
       this.noiDung = noiDung;
    }
   
     @Id 

    
    @Column(name="ID_CHUONG", unique=true, nullable=false)
    public int getIdChuong() {
        return this.idChuong;
    }
    
    public void setIdChuong(int idChuong) {
        this.idChuong = idChuong;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ANPHAM")
    public Anpham getAnpham() {
        return this.anpham;
    }
    
    public void setAnpham(Anpham anpham) {
        this.anpham = anpham;
    }

    
    @Column(name="TEN_CHUONG")
    public Serializable getTenChuong() {
        return this.tenChuong;
    }
    
    public void setTenChuong(Serializable tenChuong) {
        this.tenChuong = tenChuong;
    }

    
    @Column(name="NOI_DUNG")
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }




}


