package entity;



import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BmKytapchi generated by hbm2java
 */
@Entity
@Table(name="BM_KYTAPCHI"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class BmKytapchi  implements java.io.Serializable {


     private int idKy;
     private Anpham anpham;
     private String tenKy;
     private String urlHinh;
     private Date thoiGianDang;
     private String loiGioiThieu;

    public BmKytapchi() {
    }

	
    public BmKytapchi(int idKy) {
        this.idKy = idKy;
    }
    public BmKytapchi(int idKy, Anpham anpham, String tenKy, String urlHinh, Date thoiGianDang, String loiGioiThieu) {
       this.idKy = idKy;
       this.anpham = anpham;
       this.tenKy = tenKy;
       this.urlHinh = urlHinh;
       this.thoiGianDang = thoiGianDang;
       this.loiGioiThieu = loiGioiThieu;
    }
   
     @Id 

    
    @Column(name="ID_KY", unique=true, nullable=false)
    public int getIdKy() {
        return this.idKy;
    }
    
    public void setIdKy(int idKy) {
        this.idKy = idKy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ANPHAM")
    public Anpham getAnpham() {
        return this.anpham;
    }
    
    public void setAnpham(Anpham anpham) {
        this.anpham = anpham;
    }

    
    @Column(name="TEN_KY")
    public String getTenKy() {
        return this.tenKy;
    }
    
    public void setTenKy(String tenKy) {
        this.tenKy = tenKy;
    }

    
    @Column(name="URL_HINH")
    public String getUrlHinh() {
        return this.urlHinh;
    }
    
    public void setUrlHinh(String urlHinh) {
        this.urlHinh = urlHinh;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="THOI_GIAN_DANG", length=23)
    public Date getThoiGianDang() {
        return this.thoiGianDang;
    }
    
    public void setThoiGianDang(Date thoiGianDang) {
        this.thoiGianDang = thoiGianDang;
    }

    
    @Column(name="LOI_GIOI_THIEU")
    public String getLoiGioiThieu() {
        return this.loiGioiThieu;
    }
    
    public void setLoiGioiThieu(String loiGioiThieu) {
        this.loiGioiThieu = loiGioiThieu;
    }




}


