package entity;
// Generated Dec 12, 2014 9:07:56 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bmsophanloai generated by hbm2java
 */
@Entity
@Table(name="BMSOPHANLOAI"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Bmsophanloai  implements java.io.Serializable {


     private String idSpl;
     private String soPhanLoai;
     private Set<Anpham> anphams = new HashSet<Anpham>(0);
     private Set<Sach> saches = new HashSet<Sach>(0);

    public Bmsophanloai() {
    }

	
    public Bmsophanloai(String idSpl) {
        this.idSpl = idSpl;
    }
    public Bmsophanloai(String idSpl, String soPhanLoai, Set<Anpham> anphams, Set<Sach> saches) {
       this.idSpl = idSpl;
       this.soPhanLoai = soPhanLoai;
       this.anphams = anphams;
       this.saches = saches;
    }
   
     @Id 

    
    @Column(name="ID_SPL", unique=true, nullable=false, length=10)
    public String getIdSpl() {
        return this.idSpl;
    }
    
    public void setIdSpl(String idSpl) {
        this.idSpl = idSpl;
    }

    
    @Column(name="SO_PHAN_LOAI", length=50)
    public String getSoPhanLoai() {
        return this.soPhanLoai;
    }
    
    public void setSoPhanLoai(String soPhanLoai) {
        this.soPhanLoai = soPhanLoai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bmsophanloai")
    public Set<Anpham> getAnphams() {
        return this.anphams;
    }
    
    public void setAnphams(Set<Anpham> anphams) {
        this.anphams = anphams;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bmsophanloai")
    public Set<Sach> getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set<Sach> saches) {
        this.saches = saches;
    }




}


