package entity;
// Generated Nov 24, 2014 9:54:24 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Bmtendemuc generated by hbm2java
 */
@Entity
@Table(name="BMTENDEMUC"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Bmtendemuc  implements java.io.Serializable {

    @NotEmpty
    @Size(max = 10)
     private String idDeMuc;
    @NotEmpty
     private Serializable tenDeMuc;
     private Set<Sach> saches = new HashSet<Sach>(0);

    public Bmtendemuc() {
    }

	
    public Bmtendemuc(String idDeMuc) {
        this.idDeMuc = idDeMuc;
    }
    public Bmtendemuc(String idDeMuc, Serializable tenDeMuc, Set<Sach> saches) {
       this.idDeMuc = idDeMuc;
       this.tenDeMuc = tenDeMuc;
       this.saches = saches;
    }
   
     @Id 

    
    @Column(name="ID_DE_MUC", unique=true, nullable=false, length=10)
    public String getIdDeMuc() {
        return this.idDeMuc;
    }
    
    public void setIdDeMuc(String idDeMuc) {
        this.idDeMuc = idDeMuc;
    }

    
    @Column(name="TEN_DE_MUC")
    public Serializable getTenDeMuc() {
        return this.tenDeMuc;
    }
    
    public void setTenDeMuc(Serializable tenDeMuc) {
        this.tenDeMuc = tenDeMuc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bmtendemuc")
    public Set<Sach> getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set<Sach> saches) {
        this.saches = saches;
    }




}


