package entity;
// Generated Dec 12, 2014 5:30:45 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Boithuongthiethai generated by hbm2java
 */
@Entity
@Table(name="BOITHUONGTHIETHAI"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Boithuongthiethai  implements java.io.Serializable {


     private String idBoiThuong;
     private Docgia docgia;
     private String idVatBoiThuong;
     private Date ngayBoiThuong;
     private Serializable lyDo;
     private Serializable tinhTrang;

    public Boithuongthiethai() {
    }

	
    public Boithuongthiethai(String idBoiThuong) {
        this.idBoiThuong = idBoiThuong;
    }
    public Boithuongthiethai(String idBoiThuong, Docgia docgia, String idVatBoiThuong, Date ngayBoiThuong, Serializable lyDo, Serializable tinhTrang) {
       this.idBoiThuong = idBoiThuong;
       this.docgia = docgia;
       this.idVatBoiThuong = idVatBoiThuong;
       this.ngayBoiThuong = ngayBoiThuong;
       this.lyDo = lyDo;
       this.tinhTrang = tinhTrang;
    }
   
     @Id 

    
    @Column(name="ID_BOI_THUONG", unique=true, nullable=false, length=10)
    public String getIdBoiThuong() {
        return this.idBoiThuong;
    }
    
    public void setIdBoiThuong(String idBoiThuong) {
        this.idBoiThuong = idBoiThuong;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOC_GIA")
    public Docgia getDocgia() {
        return this.docgia;
    }
    
    public void setDocgia(Docgia docgia) {
        this.docgia = docgia;
    }

    
    @Column(name="ID_VAT_BOI_THUONG", length=10)
    public String getIdVatBoiThuong() {
        return this.idVatBoiThuong;
    }
    
    public void setIdVatBoiThuong(String idVatBoiThuong) {
        this.idVatBoiThuong = idVatBoiThuong;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NGAY_BOI_THUONG", length=10)
    public Date getNgayBoiThuong() {
        return this.ngayBoiThuong;
    }
    
    public void setNgayBoiThuong(Date ngayBoiThuong) {
        this.ngayBoiThuong = ngayBoiThuong;
    }

    
    @Column(name="LY_DO")
    public Serializable getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(Serializable lyDo) {
        this.lyDo = lyDo;
    }

    
    @Column(name="TINH_TRANG")
    public Serializable getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Serializable tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


