package entity;



import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docgia generated by hbm2java
 */
@Entity
@Table(name="DOCGIA"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Docgia  implements java.io.Serializable {


     private String msThe;

     public UserPassword userPassword;

     private Serializable hoTen;
     private Serializable tinhTrang;
     private String email;
     private Serializable loaiDocGia;
     private String imageUrl;
     private Set<Luuhanhsach> luuhanhsaches = new HashSet<Luuhanhsach>(0);
     private Set<Muontaicho> muontaichos = new HashSet<Muontaicho>(0);
     private Set<Learncommons> learncommonses = new HashSet<Learncommons>(0);
     private Set<Boithuongthiethai> boithuongthiethais = new HashSet<Boithuongthiethai>(0);
     private Set<Muonphong> muonphongs = new HashSet<Muonphong>(0);
     private Set<Dktaphuan> dktaphuans = new HashSet<Dktaphuan>(0);

    public Docgia() {
    }

	
    public Docgia(String msThe) {
        this.msThe = msThe;
    }
    public Docgia(String msThe, UserPassword userPassword, Serializable hoTen, Serializable tinhTrang, String email, Serializable loaiDocGia, String imageUrl, Set<Luuhanhsach> luuhanhsaches, Set<Muontaicho> muontaichos, Set<Learncommons> learncommonses, Set<Boithuongthiethai> boithuongthiethais, Set<Muonphong> muonphongs, Set<Dktaphuan> dktaphuans) {
       this.msThe = msThe;
       this.userPassword = userPassword;
       this.hoTen = hoTen;
       this.tinhTrang = tinhTrang;
       this.email = email;
       this.loaiDocGia = loaiDocGia;
       this.imageUrl = imageUrl;
       this.luuhanhsaches = luuhanhsaches;
       this.muontaichos = muontaichos;
       this.learncommonses = learncommonses;
       this.boithuongthiethais = boithuongthiethais;
       this.muonphongs = muonphongs;
       this.dktaphuans = dktaphuans;
    }
   
     @Id 

    
    @Column(name="MS_THE", unique=true, nullable=false, length=10)
    public String getMsThe() {
        return this.msThe;
    }
    
    public void setMsThe(String msThe) {
        this.msThe = msThe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USER")
    public UserPassword getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(UserPassword userPassword) {
        this.userPassword = userPassword;
    }

    
    @Column(name="HO_TEN")
    public Serializable getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(Serializable hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="TINH_TRANG")
    public Serializable getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Serializable tinhTrang) {
        this.tinhTrang = tinhTrang;
    }

    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="LOAI_DOC_GIA")
    public Serializable getLoaiDocGia() {
        return this.loaiDocGia;
    }
    
    public void setLoaiDocGia(Serializable loaiDocGia) {
        this.loaiDocGia = loaiDocGia;
    }

    
    @Column(name="IMAGE_URL")
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<Luuhanhsach> getLuuhanhsaches() {
        return this.luuhanhsaches;
    }
    
    public void setLuuhanhsaches(Set<Luuhanhsach> luuhanhsaches) {
        this.luuhanhsaches = luuhanhsaches;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<Muontaicho> getMuontaichos() {
        return this.muontaichos;
    }
    
    public void setMuontaichos(Set<Muontaicho> muontaichos) {
        this.muontaichos = muontaichos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<Learncommons> getLearncommonses() {
        return this.learncommonses;
    }
    
    public void setLearncommonses(Set<Learncommons> learncommonses) {
        this.learncommonses = learncommonses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<Boithuongthiethai> getBoithuongthiethais() {
        return this.boithuongthiethais;
    }
    
    public void setBoithuongthiethais(Set<Boithuongthiethai> boithuongthiethais) {
        this.boithuongthiethais = boithuongthiethais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<Muonphong> getMuonphongs() {
        return this.muonphongs;
    }
    
    public void setMuonphongs(Set<Muonphong> muonphongs) {
        this.muonphongs = muonphongs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<Dktaphuan> getDktaphuans() {
        return this.dktaphuans;
    }
    
    public void setDktaphuans(Set<Dktaphuan> dktaphuans) {
        this.dktaphuans = dktaphuans;
    }




}


