package entity;
// Generated Dec 12, 2014 5:30:45 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donhang generated by hbm2java
 */
@Entity
@Table(name="DONHANG"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Donhang  implements java.io.Serializable {


     private String idDonHang;
     private Date ngayLap;
     private String tinhTrang;
     private String diaChiGoi;
     private String hinhThucThanhToan;
     private String donViTienTe;
     private Date ngayGiaoHang;
     private Date ngayThanhToan;
     private Set<CtDonhang> ctDonhangs = new HashSet<CtDonhang>(0);

    public Donhang() {
    }

	
    public Donhang(String idDonHang) {
        this.idDonHang = idDonHang;
    }
    public Donhang(String idDonHang, Date ngayLap, String tinhTrang, String diaChiGoi, String hinhThucThanhToan, String donViTienTe, Date ngayGiaoHang, Date ngayThanhToan, Set<CtDonhang> ctDonhangs) {
       this.idDonHang = idDonHang;
       this.ngayLap = ngayLap;
       this.tinhTrang = tinhTrang;
       this.diaChiGoi = diaChiGoi;
       this.hinhThucThanhToan = hinhThucThanhToan;
       this.donViTienTe = donViTienTe;
       this.ngayGiaoHang = ngayGiaoHang;
       this.ngayThanhToan = ngayThanhToan;
       this.ctDonhangs = ctDonhangs;
    }
   
     @Id 

    
    @Column(name="ID_DON_HANG", unique=true, nullable=false, length=10)
    public String getIdDonHang() {
        return this.idDonHang;
    }
    
    public void setIdDonHang(String idDonHang) {
        this.idDonHang = idDonHang;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NGAY_LAP", length=10)
    public Date getNgayLap() {
        return this.ngayLap;
    }
    
    public void setNgayLap(Date ngayLap) {
        this.ngayLap = ngayLap;
    }

    
    @Column(name="TINH_TRANG")
    public String getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(String tinhTrang) {
        this.tinhTrang = tinhTrang;
    }

    
    @Column(name="DIA_CHI_GOI")
    public String getDiaChiGoi() {
        return this.diaChiGoi;
    }
    
    public void setDiaChiGoi(String diaChiGoi) {
        this.diaChiGoi = diaChiGoi;
    }

    
    @Column(name="HINH_THUC_THANH_TOAN")
    public String getHinhThucThanhToan() {
        return this.hinhThucThanhToan;
    }
    
    public void setHinhThucThanhToan(String hinhThucThanhToan) {
        this.hinhThucThanhToan = hinhThucThanhToan;
    }

    
    @Column(name="DON_VI_TIEN_TE", length=10)
    public String getDonViTienTe() {
        return this.donViTienTe;
    }
    
    public void setDonViTienTe(String donViTienTe) {
        this.donViTienTe = donViTienTe;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NGAY_GIAO_HANG", length=10)
    public Date getNgayGiaoHang() {
        return this.ngayGiaoHang;
    }
    
    public void setNgayGiaoHang(Date ngayGiaoHang) {
        this.ngayGiaoHang = ngayGiaoHang;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NGAY_THANH_TOAN", length=10)
    public Date getNgayThanhToan() {
        return this.ngayThanhToan;
    }
    
    public void setNgayThanhToan(Date ngayThanhToan) {
        this.ngayThanhToan = ngayThanhToan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="donhang")
    public Set<CtDonhang> getCtDonhangs() {
        return this.ctDonhangs;
    }
    
    public void setCtDonhangs(Set<CtDonhang> ctDonhangs) {
        this.ctDonhangs = ctDonhangs;
    }




}


