package entity;



import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Muontaicho generated by hbm2java
 */
@Entity
@Table(name="MUONTAICHO"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Muontaicho  implements java.io.Serializable {


     private String idMuonTc;
     private Docgia docgia;
     private Sach sach;
     private Date ngayMuon;
     private Serializable tinhTrang;

    public Muontaicho() {
    }

	
    public Muontaicho(String idMuonTc) {
        this.idMuonTc = idMuonTc;
    }
    public Muontaicho(String idMuonTc, Docgia docgia, Sach sach, Date ngayMuon, Serializable tinhTrang) {
       this.idMuonTc = idMuonTc;
       this.docgia = docgia;
       this.sach = sach;
       this.ngayMuon = ngayMuon;
       this.tinhTrang = tinhTrang;
    }
   
     @Id 

    
    @Column(name="ID_MUON_TC", unique=true, nullable=false, length=10)
    public String getIdMuonTc() {
        return this.idMuonTc;
    }
    
    public void setIdMuonTc(String idMuonTc) {
        this.idMuonTc = idMuonTc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOC_GIA")
    public Docgia getDocgia() {
        return this.docgia;
    }
    
    public void setDocgia(Docgia docgia) {
        this.docgia = docgia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SACH")
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NGAY_MUON", length=10)
    public Date getNgayMuon() {
        return this.ngayMuon;
    }
    
    public void setNgayMuon(Date ngayMuon) {
        this.ngayMuon = ngayMuon;
    }

    
    @Column(name="TINH_TRANG")
    public Serializable getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Serializable tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


