package entity;
// Generated Nov 24, 2014 9:54:24 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phong generated by hbm2java
 */
@Entity
@Table(name="PHONG"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Phong  implements java.io.Serializable {


     private String idPhong;
     private Serializable tenPhong;
     private Serializable viTri;
     private Serializable tinhTrang;
     private Set<Muonphong> muonphongs = new HashSet<Muonphong>(0);

    public Phong() {
    }

	
    public Phong(String idPhong) {
        this.idPhong = idPhong;
    }
    public Phong(String idPhong, Serializable tenPhong, Serializable viTri, Serializable tinhTrang, Set<Muonphong> muonphongs) {
       this.idPhong = idPhong;
       this.tenPhong = tenPhong;
       this.viTri = viTri;
       this.tinhTrang = tinhTrang;
       this.muonphongs = muonphongs;
    }
   
     @Id 

    
    @Column(name="ID_PHONG", unique=true, nullable=false, length=10)
    public String getIdPhong() {
        return this.idPhong;
    }
    
    public void setIdPhong(String idPhong) {
        this.idPhong = idPhong;
    }

    
    @Column(name="TEN_PHONG")
    public Serializable getTenPhong() {
        return this.tenPhong;
    }
    
    public void setTenPhong(Serializable tenPhong) {
        this.tenPhong = tenPhong;
    }

    
    @Column(name="VI_TRI")
    public Serializable getViTri() {
        return this.viTri;
    }
    
    public void setViTri(Serializable viTri) {
        this.viTri = viTri;
    }

    
    @Column(name="TINH_TRANG")
    public Serializable getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Serializable tinhTrang) {
        this.tinhTrang = tinhTrang;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phong")
    public Set<Muonphong> getMuonphongs() {
        return this.muonphongs;
    }
    
    public void setMuonphongs(Set<Muonphong> muonphongs) {
        this.muonphongs = muonphongs;
    }




}


