package entity;
// Generated Nov 24, 2014 9:54:24 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taphuan generated by hbm2java
 */
@Entity
@Table(name="TAPHUAN"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class Taphuan  implements java.io.Serializable {


     private String id;
     private Serializable hoTen;
     private String sdt;
     private Date ngayDangKy;
     private Serializable tinhTrang;
     private Serializable loaiDocGia;
     private Serializable email;

    public Taphuan() {
    }

	
    public Taphuan(String id) {
        this.id = id;
    }
    public Taphuan(String id, Serializable hoTen, String sdt, Date ngayDangKy, Serializable tinhTrang, Serializable loaiDocGia, Serializable email) {
       this.id = id;
       this.hoTen = hoTen;
       this.sdt = sdt;
       this.ngayDangKy = ngayDangKy;
       this.tinhTrang = tinhTrang;
       this.loaiDocGia = loaiDocGia;
       this.email = email;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="HO_TEN")
    public Serializable getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(Serializable hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="SDT", length=12)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NGAY_DANG_KY", length=10)
    public Date getNgayDangKy() {
        return this.ngayDangKy;
    }
    
    public void setNgayDangKy(Date ngayDangKy) {
        this.ngayDangKy = ngayDangKy;
    }

    
    @Column(name="TINH_TRANG")
    public Serializable getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Serializable tinhTrang) {
        this.tinhTrang = tinhTrang;
    }

    
    @Column(name="LOAI_DOC_GIA")
    public Serializable getLoaiDocGia() {
        return this.loaiDocGia;
    }
    
    public void setLoaiDocGia(Serializable loaiDocGia) {
        this.loaiDocGia = loaiDocGia;
    }

    
    @Column(name="EMAIL")
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }




}


