package entity;
// Generated Nov 24, 2014 9:54:24 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserPassword generated by hbm2java
 */
@Entity
@Table(name="USER_PASSWORD"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class UserPassword  implements java.io.Serializable {


     private int idUser;
     private String userName;
     private String password;
     private Serializable role;

    public UserPassword() {
    }

	
    public UserPassword(int idUser) {
        this.idUser = idUser;
    }
    public UserPassword(int idUser, String userName, String password, Serializable role) {
       this.idUser = idUser;
       this.userName = userName;
       this.password = password;
       this.role = role;
    }
   
     @Id 

    
    @Column(name="ID_USER", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="USER_NAME", length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="PASSWORD", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="ROLE")
    public Serializable getRole() {
        return this.role;
    }
    
    public void setRole(Serializable role) {
        this.role = role;
    }




}


