package entity;
// Generated Dec 12, 2014 5:30:45 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WebpagesOauthMembershipId generated by hbm2java
 */
@Embeddable
public class WebpagesOauthMembershipId  implements java.io.Serializable {


     private Serializable provider;
     private Serializable providerUserId;

    public WebpagesOauthMembershipId() {
    }

    public WebpagesOauthMembershipId(Serializable provider, Serializable providerUserId) {
       this.provider = provider;
       this.providerUserId = providerUserId;
    }
   


    @Column(name="Provider", nullable=false)
    public Serializable getProvider() {
        return this.provider;
    }
    
    public void setProvider(Serializable provider) {
        this.provider = provider;
    }


    @Column(name="ProviderUserId", nullable=false)
    public Serializable getProviderUserId() {
        return this.providerUserId;
    }
    
    public void setProviderUserId(Serializable providerUserId) {
        this.providerUserId = providerUserId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WebpagesOauthMembershipId) ) return false;
		 WebpagesOauthMembershipId castOther = ( WebpagesOauthMembershipId ) other; 
         
		 return ( (this.getProvider()==castOther.getProvider()) || ( this.getProvider()!=null && castOther.getProvider()!=null && this.getProvider().equals(castOther.getProvider()) ) )
 && ( (this.getProviderUserId()==castOther.getProviderUserId()) || ( this.getProviderUserId()!=null && castOther.getProviderUserId()!=null && this.getProviderUserId().equals(castOther.getProviderUserId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProvider() == null ? 0 : this.getProvider().hashCode() );
         result = 37 * result + ( getProviderUserId() == null ? 0 : this.getProviderUserId().hashCode() );
         return result;
   }   


}


