package entity;
// Generated Dec 12, 2014 5:30:45 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebpagesMembership generated by hbm2java
 */
@Entity
@Table(name="webpages_Membership"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class WebpagesMembership  implements java.io.Serializable {


     private int userId;
     private Date createDate;
     private Serializable confirmationToken;
     private Boolean isConfirmed;
     private Date lastPasswordFailureDate;
     private int passwordFailuresSinceLastSuccess;
     private Serializable password;
     private Date passwordChangedDate;
     private Serializable passwordSalt;
     private Serializable passwordVerificationToken;
     private Date passwordVerificationTokenExpirationDate;

    public WebpagesMembership() {
    }

	
    public WebpagesMembership(int userId, int passwordFailuresSinceLastSuccess, Serializable password, Serializable passwordSalt) {
        this.userId = userId;
        this.passwordFailuresSinceLastSuccess = passwordFailuresSinceLastSuccess;
        this.password = password;
        this.passwordSalt = passwordSalt;
    }
    public WebpagesMembership(int userId, Date createDate, Serializable confirmationToken, Boolean isConfirmed, Date lastPasswordFailureDate, int passwordFailuresSinceLastSuccess, Serializable password, Date passwordChangedDate, Serializable passwordSalt, Serializable passwordVerificationToken, Date passwordVerificationTokenExpirationDate) {
       this.userId = userId;
       this.createDate = createDate;
       this.confirmationToken = confirmationToken;
       this.isConfirmed = isConfirmed;
       this.lastPasswordFailureDate = lastPasswordFailureDate;
       this.passwordFailuresSinceLastSuccess = passwordFailuresSinceLastSuccess;
       this.password = password;
       this.passwordChangedDate = passwordChangedDate;
       this.passwordSalt = passwordSalt;
       this.passwordVerificationToken = passwordVerificationToken;
       this.passwordVerificationTokenExpirationDate = passwordVerificationTokenExpirationDate;
    }
   
     @Id 

    
    @Column(name="UserId", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="ConfirmationToken")
    public Serializable getConfirmationToken() {
        return this.confirmationToken;
    }
    
    public void setConfirmationToken(Serializable confirmationToken) {
        this.confirmationToken = confirmationToken;
    }

    
    @Column(name="IsConfirmed")
    public Boolean getIsConfirmed() {
        return this.isConfirmed;
    }
    
    public void setIsConfirmed(Boolean isConfirmed) {
        this.isConfirmed = isConfirmed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastPasswordFailureDate", length=23)
    public Date getLastPasswordFailureDate() {
        return this.lastPasswordFailureDate;
    }
    
    public void setLastPasswordFailureDate(Date lastPasswordFailureDate) {
        this.lastPasswordFailureDate = lastPasswordFailureDate;
    }

    
    @Column(name="PasswordFailuresSinceLastSuccess", nullable=false)
    public int getPasswordFailuresSinceLastSuccess() {
        return this.passwordFailuresSinceLastSuccess;
    }
    
    public void setPasswordFailuresSinceLastSuccess(int passwordFailuresSinceLastSuccess) {
        this.passwordFailuresSinceLastSuccess = passwordFailuresSinceLastSuccess;
    }

    
    @Column(name="Password", nullable=false)
    public Serializable getPassword() {
        return this.password;
    }
    
    public void setPassword(Serializable password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PasswordChangedDate", length=23)
    public Date getPasswordChangedDate() {
        return this.passwordChangedDate;
    }
    
    public void setPasswordChangedDate(Date passwordChangedDate) {
        this.passwordChangedDate = passwordChangedDate;
    }

    
    @Column(name="PasswordSalt", nullable=false)
    public Serializable getPasswordSalt() {
        return this.passwordSalt;
    }
    
    public void setPasswordSalt(Serializable passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    
    @Column(name="PasswordVerificationToken")
    public Serializable getPasswordVerificationToken() {
        return this.passwordVerificationToken;
    }
    
    public void setPasswordVerificationToken(Serializable passwordVerificationToken) {
        this.passwordVerificationToken = passwordVerificationToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PasswordVerificationTokenExpirationDate", length=23)
    public Date getPasswordVerificationTokenExpirationDate() {
        return this.passwordVerificationTokenExpirationDate;
    }
    
    public void setPasswordVerificationTokenExpirationDate(Date passwordVerificationTokenExpirationDate) {
        this.passwordVerificationTokenExpirationDate = passwordVerificationTokenExpirationDate;
    }




}


