package entity;



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WebpagesOauthMembership generated by hbm2java
 */
@Entity
@Table(name="webpages_OAuthMembership"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
)
public class WebpagesOauthMembership  implements java.io.Serializable {


     private WebpagesOauthMembershipId id;
     private int userId;

    public WebpagesOauthMembership() {
    }

    public WebpagesOauthMembership(WebpagesOauthMembershipId id, int userId) {
       this.id = id;
       this.userId = userId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="provider", column=@Column(name="Provider", nullable=false) ), 
        @AttributeOverride(name="providerUserId", column=@Column(name="ProviderUserId", nullable=false) ) } )
    public WebpagesOauthMembershipId getId() {
        return this.id;
    }
    
    public void setId(WebpagesOauthMembershipId id) {
        this.id = id;
    }

    
    @Column(name="UserId", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }




}


