package entity;
// Generated Nov 24, 2014 9:54:24 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WebpagesRoles generated by hbm2java
 */
@Entity
@Table(name="webpages_Roles"
    ,schema="dbo"
    ,catalog="QLTHUVIEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="RoleName") 
)
public class WebpagesRoles  implements java.io.Serializable {


     private int roleId;
     private Serializable roleName;
     private Set<UserProfile> userProfiles = new HashSet<UserProfile>(0);

    public WebpagesRoles() {
    }

	
    public WebpagesRoles(int roleId, Serializable roleName) {
        this.roleId = roleId;
        this.roleName = roleName;
    }
    public WebpagesRoles(int roleId, Serializable roleName, Set<UserProfile> userProfiles) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.userProfiles = userProfiles;
    }
   
     @Id 

    
    @Column(name="RoleId", unique=true, nullable=false)
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="RoleName", unique=true, nullable=false)
    public Serializable getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(Serializable roleName) {
        this.roleName = roleName;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="webpagesRoleses")
    public Set<UserProfile> getUserProfiles() {
        return this.userProfiles;
    }
    
    public void setUserProfiles(Set<UserProfile> userProfiles) {
        this.userProfiles = userProfiles;
    }




}


